project:
  type: book

book:
  title: "R for the PPL(E)"
  author: "David Fleming"
  chapters:
    - index.qmd
    - part: "The basics"
      chapters: 
        - 1_r_markdown_basics.qmd
        - 2_r_firstdata.qmd
        - 3_r_plotting.qmd
        - 4_r_knitting.qmd
    - part: "Introduction to Statistical Analysis (Y1)"
      chapters: 
        - 5_r_ISA1.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

editor: visual

