project:
  type: book
  output-dir: docs

book:
  title: "R for the PPL(E)"
  author: "The PPLE ISA team"
  date: last-modified
  date-format: long
  license: "CC BY-SA"
  page-footer: CC-BY-SA-4.0 (2025) David Fleming
  repo-url: https://github.com/dvlaming/R4PPLE
  repo-actions: [issue, source]
  chapters:
    - index.qmd
    - part: "The basics"
      chapters: 
        - 1_r_markdown_basics.qmd
        - 2_r_firstdata.qmd
        - 3_r_plotting.qmd
        - 4_r_knitting.qmd
    - part: "Introduction to Statistical Analysis (Y1)"
      chapters:
        - r_ISA_preface.qmd
        - 5_r_ISA1.qmd
        - 6_r_ISA2.qmd
        - 7_r_ISA3.qmd
        - 8_r_ISA4.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    css: tablecapz.css


